FEATURES:
- plays_offense_home
- drives_offense_home
- ppa_offense_home
- total_ppa_offense_home
- success_rate_offense_home
- explosiveness_offense_home
- power_success_offense_home
- stuff_rate_offense_home
- line_yards_offense_home
- line_yards_total_offense_home
- second_level_yards_offense_home
- second_level_yards_total_offense_home
- open_field_yards_offense_home
- open_field_yards_total_offense_home
- standard_downs.ppa_offense_home
- standard_downs.success_rate_offense_home
- standard_downs.explosiveness_offense_home
- passing_downs.ppa_offense_home
- passing_downs.success_rate_offense_home
- passing_downs.explosiveness_offense_home
- rushing_plays.ppa_offense_home
- rushing_plays.total_ppa_offense_home
- rushing_plays.success_rate_offense_home
- rushing_plays.explosiveness_offense_home
- passing_plays.ppa_offense_home
- passing_plays.total_ppa_offense_home
- passing_plays.success_rate_offense_home
- passing_plays.explosiveness_offense_home
- plays_defense_home
- drives_defense_home
- ppa_defense_home
- total_ppa_defense_home
- success_rate_defense_home
- explosiveness_defense_home
- power_success_defense_home
- stuff_rate_defense_home
- line_yards_defense_home
- line_yards_total_defense_home
- second_level_yards_defense_home
- second_level_yards_total_defense_home
- open_field_yards_defense_home
- open_field_yards_total_defense_home
- standard_downs.ppa_defense_home
- standard_downs.success_rate_defense_home
- standard_downs.explosiveness_defense_home
- passing_downs.ppa_defense_home
- passing_downs.success_rate_defense_home
- passing_downs.explosiveness_defense_home
- rushing_plays.ppa_defense_home
- rushing_plays.total_ppa_defense_home
- rushing_plays.success_rate_defense_home
- rushing_plays.explosiveness_defense_home
- passing_plays.ppa_defense_home
- passing_plays.total_ppa_defense_home
- passing_plays.success_rate_defense_home
- passing_plays.explosiveness_defense_home
- plays_offense_away
- drives_offense_away
- ppa_offense_away
- total_ppa_offense_away
- success_rate_offense_away
- explosiveness_offense_away
- power_success_offense_away
- stuff_rate_offense_away
- line_yards_offense_away
- line_yards_total_offense_away
- second_level_yards_offense_away
- second_level_yards_total_offense_away
- open_field_yards_offense_away
- open_field_yards_total_offense_away
- standard_downs.ppa_offense_away
- standard_downs.success_rate_offense_away
- standard_downs.explosiveness_offense_away
- passing_downs.ppa_offense_away
- passing_downs.success_rate_offense_away
- passing_downs.explosiveness_offense_away
- rushing_plays.ppa_offense_away
- rushing_plays.total_ppa_offense_away
- rushing_plays.success_rate_offense_away
- rushing_plays.explosiveness_offense_away
- passing_plays.ppa_offense_away
- passing_plays.total_ppa_offense_away
- passing_plays.success_rate_offense_away
- passing_plays.explosiveness_offense_away
- plays_defense_away
- drives_defense_away
- ppa_defense_away
- total_ppa_defense_away
- success_rate_defense_away
- explosiveness_defense_away
- power_success_defense_away
- stuff_rate_defense_away
- line_yards_defense_away
- line_yards_total_defense_away
- second_level_yards_defense_away
- second_level_yards_total_defense_away
- open_field_yards_defense_away
- open_field_yards_total_defense_away
- standard_downs.ppa_defense_away
- standard_downs.success_rate_defense_away
- standard_downs.explosiveness_defense_away
- passing_downs.ppa_defense_away
- passing_downs.success_rate_defense_away
- passing_downs.explosiveness_defense_away
- rushing_plays.ppa_defense_away
- rushing_plays.total_ppa_defense_away
- rushing_plays.success_rate_defense_away
- rushing_plays.explosiveness_defense_away
- passing_plays.ppa_defense_away
- passing_plays.total_ppa_defense_away
- passing_plays.success_rate_defense_away
- passing_plays.explosiveness_defense_away

TARGET: Diff